"""add room inventory structure

Revision ID: 0bcdbba11e6b
Revises: 644feb3b7604
Create Date: 2026-09-07 23:36:10.147323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bcdbba11e6b'
down_revision: Union[str, Sequence[str], None] = '644feb3b7604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cottage_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('base_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cottage_id'], ['cottages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cottage_id', 'code', name='uq_rooms_cottage_code')
    )
    op.create_index(op.f('ix_rooms_cottage_id'), 'rooms', ['cottage_id'], unique=False)
    op.alter_column('cottages', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cottages', 'base_rate',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.add_column('reservations', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reservations', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_column('reservations', 'room_id')
    op.alter_column('cottages', 'base_rate',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('cottages', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_rooms_cottage_id'), table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###
